version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/city"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/hotrank"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/htct"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/mab"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/smab"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/stats"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/sv"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/ut"
    schedule:
      # daily
      interval: "weekly"