version: 2
updates:

  - package-ecosystem: "gomod"
    directory: "/pipe"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/ut"
    schedule:
      # daily
      interval: "weekly"