name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
#
#    - name: Test ut
#      run: go test -v ./...
#
#    - name: Test sv
#      run: go test -v sv/...
#
#    - name: Test logger
#      run: go test -v logger/...
#
#    - name: Test htct
#      run: go test -v htct/...
#
#    - name: Test city
#      run: go test -v city/...
